openapi: 3.0.0
info:
  title: 강의 상세 관련 API
  description: 강의 상세와 관련된 API입니다.
  version: 1.0.0
paths:
  /lectures/{lectureId}/rating-stats:
    get:
      summary: 별점 통계 조회
      description: 강의의 별점 통계를 조회합니다. (강의의 고유 ID 필요)
      tags:
        - 강의 상세 관련
      parameters:
        - in: path
          name: lectureId
          required: true
          description: 강의의 고유 ID
          schema:
            type: integer
      responses:
        '200':
          description: 별점 통계 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      averageRating:
                        type: number
                        format: float
                        example: 4.25
                      ratingCount:
                        type: object
                        properties:
                          5:
                            type: integer
                            example: 17
                          4:
                            type: integer
                            example: 9
                          3:
                            type: integer
                            example: 5
                          2:
                            type: integer
                            example: 1
                          1:
                            type: integer
                            example: 0
                      totalReviews:
                        type: integer
                        example: 32
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request

  /comments/{commentId}/recommend:
    post:
      summary: 추천하기
      description: 댓글에 추천을 추가합니다. (댓글 ID 필요)
      tags:
        - 강의 상세 관련
      parameters:
        - in: path
          name: commentId
          required: true
          description: 댓글의 고유 ID
          schema:
            type: integer
      responses:
        '200':
          description: 추천이 성공적으로 완료되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                  code:
                    type: integer
                  message:
                    type: string
                  result:
                    type: object
                    properties:
                      commentId:
                        type: integer
                        example: 1
                      totalRecommendations:
                        type: integer
                        example: 15
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request
