openapi: 3.0.0
info:
  title: 강의별 리뷰 조회 API
  description: 특정 강의 추천순, 최신순, 별점별 리뷰 조회 API
  version: 1.0.0
paths:
  /lectures/{lectureId}/reviews/recommended:
    get:
      summary: 특정 강의의 추천순 리뷰 조회
      description: |
        한 페이지에 표시할 리뷰 개수와 페이지 번호 지정 가능
      tags:
        - 강의별 리뷰 조회
      parameters:
        - in: path
          name: lectureId
          description: "강의ID"
          required: true
          schema:
            type: integer
            example: 101
        - in: query
          name: limit
          description: "한 페이지에 표시할 리뷰 개수 (기본값: 5)"
          required: false
          schema:
            type: integer
            default: 5
            example: 5
        - in: query
          name: page
          description: "페이지 번호 (1부터 시작, 기본값: 1)"
          required: false
          schema:
            type: integer
            default: 1
            example: 1
      responses:
        "200":
          description: 추천순 리뷰 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 추천순 리뷰 조회 성공
                  result:
                    type: object
                    properties:
                      totalReviews:
                        type: integer
                        description: 전체 리뷰 개수
                        example: 25
                      totalPages:
                        type: integer
                        description: 전체 페이지 수
                        example: 5
                      currentPage:
                        type: integer
                        description: 현재 페이지 번호
                        example: 1
                      reviews:
                        type: array
                        items:
                          type: object
                          properties:
                            rating:
                              type: integer
                              description: 별점
                              example: 5
                            date:
                              type: string
                              format: date
                              description: 리뷰 작성일
                              example: 2024-10-01
                            duration:
                              type: string
                              description: 공부 기간
                              example: "일주일 이내"
                            reviewContent:
                              type: string
                              description: 리뷰 내용
                              example: "리뷰내용입니다"
                            recommendations:
                              type: integer
                              description: 추천 수
                              example: 5
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request

  /lectures/{lectureId}/reviews/latest:
    get:
      summary: 특정 강의의 최신순 리뷰 조회
      description: |
        한 페이지에 표시할 리뷰 개수와 페이지 번호 지정 가능
      tags:
        - 강의별 리뷰 조회
      parameters:
        - in: path
          name: lectureId
          description: "강의ID"
          required: true
          schema:
            type: integer
            example: 101
        - in: query
          name: limit
          description: "한 페이지에 표시할 리뷰 개수 (기본값: 5)"
          required: false
          schema:
            type: integer
            default: 5
            example: 5
        - in: query
          name: page
          description: "페이지 번호 (1부터 시작, 기본값: 1)"
          required: false
          schema:
            type: integer
            default: 1
            example: 1
      responses:
        "200":
          description: 최신순 리뷰 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 최신순 리뷰 조회 성공
                  result:
                    type: object
                    properties:
                      totalReviews:
                        type: integer
                        description: 전체 리뷰 개수
                        example: 50
                      totalPages:
                        type: integer
                        description: 전체 페이지 수
                        example: 10
                      currentPage:
                        type: integer
                        description: 현재 페이지 번호
                        example: 1
                      reviews:
                        type: array
                        items:
                          type: object
                          properties:
                            rating:
                              type: integer
                              description: 별점
                              example: 4
                            date:
                              type: string
                              format: date
                              description: 리뷰 작성일
                              example: 2024-11-01
                            duration:
                              type: string
                              description: 공부 기간
                              example: "3달 이내"
                            reviewContent:
                              type: string
                              description: 리뷰 내용
                              example: "리뷰내용입니다"
                            recommendations:
                              type: integer
                              description: 추천 수
                              example: 42
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request

  # /lectures/{lectureId}/reviews/by-rating:
  #   get:
  #     summary: 특정 강의의 별점별 리뷰 조회
  #     description: |
  #       한 페이지에 표시할 리뷰 개수와 페이지 번호 지정 가능
  #     tags:
  #       - 강의별 리뷰 조회
  #     parameters:
  #       - in: path
  #         name: lectureId
  #         description: "강의ID"
  #         required: true
  #         schema:
  #           type: integer
  #           example: 101
  #       - in: query
  #         name: rating
  #         description: "필터링할 별점 (1~5)"
  #         required: true
  #         schema:
  #           type: integer
  #           minimum: 1
  #           maximum: 5
  #           example: 5
  #       - in: query
  #         name: limit
  #         description: "한 페이지에 표시할 리뷰 개수 (기본값: 5)"
  #         required: false
  #         schema:
  #           type: integer
  #           default: 5
  #           example: 5
  #       - in: query
  #         name: page
  #         description: "페이지 번호 (1부터 시작, 기본값: 1)"
  #         required: false
  #         schema:
  #           type: integer
  #           default: 1
  #           example: 1
  #     responses:
  #       "200":
  #         description: 별점별 리뷰 조회 성공
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 isSuccess:
  #                   type: boolean
  #                   example: true
  #                 code:
  #                   type: integer
  #                   example: 200
  #                 message:
  #                   type: string
  #                   example: 별점별 리뷰 조회 성공
  #                 result:
  #                   type: object
  #                   properties:
  #                     totalReviews:
  #                       type: integer
  #                       description: 전체 리뷰 개수
  #                       example: 20
  #                     totalPages:
  #                       type: integer
  #                       description: 전체 페이지 수
  #                       example: 4
  #                     currentPage:
  #                       type: integer
  #                       description: 현재 페이지 번호
  #                       example: 1
  #                     reviews:
  #                       type: array
  #                       items:
  #                         type: object
  #                         properties:
  #                           rating:
  #                             type: integer
  #                             description: 별점
  #                             example: 5
  #                           date:
  #                             type: string
  #                             format: date
  #                             description: 리뷰 작성일
  #                             example: 2024-10-15
  #                           duration:
  #                             type: string
  #                             description: 공부 기간
  #                             example: "6달 이내"
  #                           reviewContent:
  #                             type: string
  #                             description: 리뷰 내용
  #                             example: "리뷰내용입니다"
  #                           recommendations:
  #                             type: integer
  #                             description: 추천 수
  #                             example: 7
  #       "400":
  #         description: 잘못된 요청
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 error:
  #                   type: string
  #                   example: Invalid request
