openapi: 3.0.0
info:
  title: 강의 검색 API
  description: 사용자가 입력한 키워드로 강의를 검색할 수 있는 API입니다.
  version: 1.0.0
paths:
  /lectures/search:
    get:
      summary: 강의 검색
      description: |
        사용자가 입력한 검색어를 기준으로 강의 목록을 검색합니다.
        강의명, 강사명, 플랫폼명으로 필터링할 수 있습니다.
      tags:
        - 강의 검색
      parameters:
        - in: query
          name: keyword
          description: 검색할 키워드 (강의명, 강사명, 플랫폼명 중 하나)
          required: true
          schema:
            type: string
            example: "JavaScript"
        - in: query
          name: platform
          description: 특정 플랫폼으로 필터링 (선택)
          required: false
          schema:
            type: string
            example: "클래스101"
        - in: query
          name: instructor
          description: 특정 강사의 강의로 필터링 (선택)
          required: false
          schema:
            type: string
            example: "김강사"
        - in: query
          name: limit
          description: 검색 결과의 최대 개수 제한 (선택)
          required: false
          schema:
            type: integer
            example: 10
        - in: query
          name: offset
          description: 검색 결과 시작 위치 (페이징 처리에 사용)
          required: false
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: 강의 검색 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 강의 검색 성공
                  result:
                    type: object
                    properties:
                      totalCount:
                        type: integer
                        description: 검색된 강의 총 개수
                        example: 42
                      lectures:
                        type: array
                        items:
                          type: object
                          properties:
                            lectureId:
                              type: integer
                              description: 강의 고유 ID
                              example: 123
                            lectureName:
                              type: string
                              description: 강의명
                              example: JavaScript 입문 강의
                            instructorName:
                              type: string
                              description: 강사명
                              example: 김강사
                            platform:
                              type: string
                              description: 플랫폼명
                              example: 클래스101
                            rating:
                              type: number
                              format: float
                              description: 평균 별점
                              example: 4.8
                            reviewCount:
                              type: integer
                              description: 리뷰 개수
                              example: 25
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request
