openapi: 3.0.0
info:
  title: 리뷰 조회 API
  description: 리뷰를 추천순, 최신순, 별점별로 조회할 수 있는 API입니다.
  version: 1.0.0
paths:
  /reviews/recommended:
    get:
      summary: 추천순 리뷰 조회
      description: |
        리뷰를 추천 수 기준으로 정렬하여 반환합니다.
        개수 제한(limit)에 따라 4개 또는 전체 리뷰를 반환합니다.
      tags:
        - 리뷰 조회
      parameters:
        - in: query
          name: limit
          description: 반환할 리뷰의 개수 제한. 값이 없으면 전체 리뷰를 반환합니다.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 추천순 리뷰 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 추천순 리뷰 조회 성공
                  result:
                    type: object
                    properties:
                      reviews:
                        type: array
                        items:
                          type: object
                          properties:
                            lectureName:
                              type: string
                              example: 강의명
                            instructorName:
                              type: string
                              example: 강사명
                            platform:
                              type: string
                              example: 클래스101
                            rating:
                              type: integer
                              example: 5
                            review:
                              type: string
                              example: "이 강의 정말 추천합니다."
                            recommendations:
                              type: integer
                              example: 123
                            date:
                              type: string
                              format: date
                              example: 2024-10-01
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request

  /reviews/latest:
    get:
      summary: 최신순 리뷰 조회
      description: |
        리뷰를 최신 작성일 기준으로 정렬하여 반환합니다.
        개수 제한(limit)에 따라 4개 또는 전체 리뷰를 반환합니다.
      tags:
        - 리뷰 조회
      parameters:
        - in: query
          name: limit
          description: 반환할 리뷰의 개수 제한. 값이 없으면 전체 리뷰를 반환합니다.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 최신순 리뷰 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 최신순 리뷰 조회 성공
                  result:
                    type: object
                    properties:
                      reviews:
                        type: array
                        items:
                          type: object
                          properties:
                            lectureName:
                              type: string
                              example: 강의명
                            instructorName:
                              type: string
                              example: 강사명
                            platform:
                              type: string
                              example: 클래스101
                            rating:
                              type: integer
                              example: 4
                            review:
                              type: string
                              example: "좋은 강의입니다. 추천합니다!"
                            date:
                              type: string
                              format: date
                              example: 2024-11-01
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request

  /reviews/by-rating:
    get:
      summary: 별점별 리뷰 조회
      description: |
        특정 별점(1~5)에 해당하는 리뷰를 필터링하여 반환합니다.
        개수 제한(limit)에 따라 4개 또는 전체 리뷰를 반환합니다.
      tags:
        - 리뷰 조회
      parameters:
        - in: query
          name: rating
          description: 필터링할 별점 (1~5 사이 정수)
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 5
        - in: query
          name: limit
          description: 반환할 리뷰의 개수 제한. 값이 없으면 전체 리뷰를 반환합니다.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 별점별 리뷰 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 별점별 리뷰 조회 성공
                  result:
                    type: object
                    properties:
                      reviews:
                        type: array
                        items:
                          type: object
                          properties:
                            lectureName:
                              type: string
                              example: 강의명
                            instructorName:
                              type: string
                              example: 강사명
                            platform:
                              type: string
                              example: 클래스101
                            rating:
                              type: integer
                              example: 5
                            review:
                              type: string
                              example: "이 강의는 정말 최고입니다."
                            date:
                              type: string
                              format: date
                              example: 2024-10-15
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request
